name: ledger_flutter_plus
description: A Flutter plugin to scan, connect & sign transactions using your Ledger Nano devices
version: 1.2.3
homepage: https://developers.ledger.com/
repository: https://github.com/vespr-wallet/ledger-flutter-plus
issue_tracker: https://github.com/vespr-wallet/ledger-flutter-plus/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.1.0
  universal_ble: ^0.12.0 # ">=0.11.0 <= 0.12.0"
  ledger_usb_plus: ^1.0.2
  rxdart: ^0.28.0
  collection: ^1.18.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0

flutter:

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:
