name: ledger_flutter_plus
description: A Flutter plugin to scan, connect & sign transactions using your Ledger Nano devices
version: 1.0.5
homepage: https://developers.ledger.com/
repository: https://github.com/vespr-wallet/ledger-flutter-plus
issue_tracker: https://github.com/vespr-wallet/ledger-flutter-plus/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.1.0
  universal_ble: ^0.10.0
  ledger_usb_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
